# Generated by Django 3.2.4 on 2021-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('KARATE', 'KARATE'), ('STANDARD', 'STANDARD')], max_length=30)),
            ],
        ),
    ]
