# Generated by Django 3.2.4 on 2021-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('15', '15'), ('30', '30')], max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Training',
            new_name='TrainingType',
        ),
    ]
