# Generated by Django 3.2.4 on 2021-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20210618_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingDuration',
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='duration',
            field=models.CharField(choices=[('15', '15'), ('30', '30')], default='15', max_length=30),
        ),
    ]
