# Generated by Django 3.2.4 on 2021-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20210622_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('15', '15'), ('30', '30')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingtype',
            name='duration',
        ),
    ]
