# Generated by Django 3.2.4 on 2021-06-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20210622_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingDuration',
        ),
        migrations.DeleteModel(
            name='TrainingType',
        ),
    ]
